name: Tests

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          getconf -a | grep CACHE
          g++ main.cpp page_traverser.cpp mem_utils.cpp -O3 -std=gnu++20 -DVERBOSE
          ./a.out
        name: Measure Cache stats
